// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xcFTM2Ofs9HbYcHn1ihruRnNyPZxPsQ',
    appId: '1:672370746332:web:0cb33c4f9cd59fbf2b6519',
    messagingSenderId: '672370746332',
    projectId: 'zensar-recipe-app',
    authDomain: 'zensar-recipe-app.firebaseapp.com',
    storageBucket: 'zensar-recipe-app.appspot.com',
    measurementId: 'G-LNRWM1NSYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8kFwMnaNtO348jPL4xVTbgUZu-yF4ULg',
    appId: '1:672370746332:android:cb90b6d9d89d776a2b6519',
    messagingSenderId: '672370746332',
    projectId: 'zensar-recipe-app',
    storageBucket: 'zensar-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOBe319CqPeiBjWYxUM8Z5pAHByujXQ9w',
    appId: '1:672370746332:ios:01d747307e37c6702b6519',
    messagingSenderId: '672370746332',
    projectId: 'zensar-recipe-app',
    storageBucket: 'zensar-recipe-app.appspot.com',
    iosClientId: '672370746332-dnrpjqjbu0427l5uajb2ock83sjk8mvg.apps.googleusercontent.com',
    iosBundleId: 'com.zensar.recipeapp.zensarRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOBe319CqPeiBjWYxUM8Z5pAHByujXQ9w',
    appId: '1:672370746332:ios:01d747307e37c6702b6519',
    messagingSenderId: '672370746332',
    projectId: 'zensar-recipe-app',
    storageBucket: 'zensar-recipe-app.appspot.com',
    iosClientId: '672370746332-dnrpjqjbu0427l5uajb2ock83sjk8mvg.apps.googleusercontent.com',
    iosBundleId: 'com.zensar.recipeapp.zensarRecipeApp',
  );
}
